remote_theme: "mmistakes/minimal-mistakes@4.21.0"
minimal_mistakes_skin: "dark"
locale: "en-GB"
title: "BibblyBobblyBlogs"
plugins:
 - jekyll-include-cache

author:
 name : "Benjamin Mawdsley"
# avatar: "assets/onthebeers.jpg"
 bio: "Data Scientist with a background in cosmology."
# location : "Usually quite lost" 
defaults:
  # _posts
  - scope:
      path: ""
      type: posts
    values:
      layout: single
      author_profile: true
      read_time: true
markdown: kramdown
kramdown:
    math_engine: katex
